########################
#                      #
# MatD Makefile.config #
#                      #
########################
FC = mpif90
FFLAGS = -O2 -i8
LIBS := -L/opt/scalapack -lscalapack64 -lm
LIBS += -L$(MKLROOT)/lib -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -lpthread -lm

MATD_DIR = /Users/YO/study/program/MatD
MATD_LIB = $(MATD_DIR)/lib
MATD_INCLUDE = $(MATD_DIR)/include
CFLAGS=

