########################
#                      #
# MatD Makefile.config #
#                      #
########################
FC = mpiifort
FFLAGS = -O2
LIBS = -mkl

MATD_DIR = /home/ohnishi/MatD
MATD_LIB = $(MATD_DIR)/lib
MATD_INCLUDE = $(MATD_DIR)/include
CFLAGS=

