########################
#                      #
# MatD Makefile.config #
#                      #
########################
FC = mpiifort
FFLAGS = -O2 -i4 -openmp -mkl=parallel
LIBS = -L/opt/intel/composer_xe_2013.5.192/mkl/lib/intel64 -lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64 -lpthread -lm -ldl

MATD_DIR = /home/ohnishi/MatD
MATD_LIB = $(MATD_DIR)/lib
MATD_INCLUDE = $(MATD_DIR)/include
CFLAGS =
DPPFLAGS = -DINT4
